import React, { createContext, useContext, useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { BrowserRouter, Link, Route, Routes, useLocation, useNavigate, useParams } from 'react-router-dom'
import {
  ArrowRight, BookOpen, ChevronDown, Heart, Menu, Search, ShoppingBag, Sparkles, Star, Truck, X, Zap
} from 'lucide-react'
import './styles.css'

const books = [
  { id: 1, title: 'The Midnight Library', author: 'Matt Haig', price: 1895, oldPrice: 2495, category: 'Fiction', badge: 'Bestseller', image: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&w=600&q=85', accent: '#d9e4df' },
  { id: 2, title: 'Tomorrow, and Tomorrow, and Tomorrow', author: 'Gabrielle Zevin', price: 2295, oldPrice: 2995, category: 'Fiction', badge: 'New', image: 'https://images.unsplash.com/photo-1511108690759-009324a90311?auto=format&fit=crop&w=600&q=85', accent: '#f0ded0' },
  { id: 3, title: 'Atomic Habits', author: 'James Clear', price: 1695, oldPrice: 2195, category: 'Self Help', badge: 'Popular', image: 'https://images.unsplash.com/photo-1553729459-efe14ef6055d?auto=format&fit=crop&w=600&q=85', accent: '#e9d8d5' },
  { id: 4, title: 'The Creative Act', author: 'Rick Rubin', price: 2495, oldPrice: 2995, category: 'Art & Design', badge: 'Staff pick', image: 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&w=600&q=85', accent: '#d5e0eb' },
  { id: 5, title: 'Ikigai', author: 'Héctor García', price: 1295, oldPrice: 1695, category: 'Self Help', badge: '20% off', image: 'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?auto=format&fit=crop&w=600&q=85', accent: '#e5e2cb' },
  { id: 6, title: 'A Brief History of Time', author: 'Stephen Hawking', price: 1995, oldPrice: 2495, category: 'Science', badge: 'Classic', image: 'https://images.unsplash.com/photo-1532012197267-da84d127e765?auto=format&fit=crop&w=600&q=85', accent: '#d8d7e6' },
  { id: 7, title: 'The Book of Form and Emptiness', author: 'Ruth Ozeki', price: 2150, oldPrice: 2695, category: 'Fiction', badge: 'New', image: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=600&q=85', accent: '#e6d6d6' },
  { id: 8, title: 'The Almanack of Naval Ravikant', author: 'Eric Jorgenson', price: 1795, oldPrice: 2395, category: 'Business', badge: 'Popular', image: 'https://images.unsplash.com/photo-1535398089889-dd807df1dfaa?auto=format&fit=crop&w=600&q=85', accent: '#d8e1d2' }
]
const categories = [
  ['Fiction', 'Stories for every kind of reader', 'https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&w=900&q=85'],
  ['Self Help', 'Small ideas, big shifts', 'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?auto=format&fit=crop&w=900&q=85'],
  ['Art & Design', 'Make room for imagination', 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&w=900&q=85'],
  ['Children', 'Wonderful worlds to grow into', 'https://images.unsplash.com/photo-1472162072942-cd5147eb3902?auto=format&fit=crop&w=900&q=85']
]
const collections = ['Manga', 'Romance', 'History', 'Philosophy', 'Thriller', 'Biographies', 'Poetry']

const StoreContext = createContext(null)
function StoreProvider({ children }) {
  const [cart, setCart] = useState(() => JSON.parse(localStorage.getItem('book-cart') || '[]'))
  const [wishlist, setWishlist] = useState(() => JSON.parse(localStorage.getItem('book-wishlist') || '[]'))
  useEffect(() => localStorage.setItem('book-cart', JSON.stringify(cart)), [cart])
  useEffect(() => localStorage.setItem('book-wishlist', JSON.stringify(wishlist)), [wishlist])
  const addToCart = (book) => setCart(items => items.some(item => item.id === book.id) ? items.map(item => item.id === book.id ? { ...item, qty: item.qty + 1 } : item) : [...items, { ...book, qty: 1 }])
  const removeFromCart = (id) => setCart(items => items.filter(item => item.id !== id))
  const toggleWishlist = (book) => setWishlist(items => items.some(item => item.id === book.id) ? items.filter(item => item.id !== book.id) : [...items, book])
  const cartCount = cart.reduce((total, item) => total + item.qty, 0)
  return <StoreContext.Provider value={{ cart, wishlist, addToCart, removeFromCart, toggleWishlist, cartCount }}>{children}</StoreContext.Provider>
}
const useStore = () => useContext(StoreContext)
const money = value => `Rs ${value.toLocaleString('en-PK')}`

function Header({ onCart }) {
  const { cartCount, wishlist } = useStore(); const [query, setQuery] = useState(''); const [open, setOpen] = useState(false); const navigate = useNavigate()
  const matches = books.filter(book => `${book.title} ${book.author}`.toLowerCase().includes(query.toLowerCase())).slice(0, 4)
  return <>
    <div className="offer"><span><Zap size={14} fill="currentColor" /> Weekend reading: enjoy 10% off with code <b>TURN THE PAGE</b></span><button onClick={() => document.querySelector('.offer')?.remove()}><X size={15} /></button></div>
    <div className="info-strip"><span>Curated books, delivered across Pakistan</span><span>Questions? hello@liberty-demo.pk &nbsp; | &nbsp; +92 21 111 444 111</span></div>
    <header className="site-header"><Link className="brand" to="/"><span className="brand-mark"><BookOpen size={22} /></span><span>LIBERTY<small>BOOKS</small></span></Link>
      <div className="search-wrap"><Search size={19} /><input value={query} onChange={e => { setQuery(e.target.value); setOpen(true) }} onFocus={() => setOpen(true)} placeholder="Search by title, author or ISBN" />{query && <button className="clear-search" onClick={() => setQuery('')}><X size={15} /></button>}
        {open && query && <div className="search-results">{matches.length ? matches.map(book => <button key={book.id} onClick={() => { navigate(`/product/${book.id}`); setOpen(false); setQuery('') }}><img src={book.image} alt="" /><span><b>{book.title}</b><small>{book.author}</small></span><strong>{money(book.price)}</strong></button>) : <div className="empty-search">No books found. <Link to="/request">Request a title</Link></div>}<Link className="all-results" to={`/search?q=${query}`}>View all results <ArrowRight size={15} /></Link></div>}
      </div>
      <nav className="header-actions"><Link to="/wishlist" aria-label="Wishlist"><Heart size={21} /><span className="action-label">Wishlist</span>{wishlist.length > 0 && <em>{wishlist.length}</em>}</Link><button onClick={onCart} aria-label="Open cart"><ShoppingBag size={21} /><span className="action-label">Bag</span>{cartCount > 0 && <em>{cartCount}</em>}</button><Link className="account-link" to="/login">Sign in <ArrowRight size={15} /></Link></nav>
      <button className="mobile-menu" onClick={() => setOpen(!open)}><Menu size={23} /></button>
    </header>
    <nav className="category-nav"><Link to="/">Home</Link><Link to="/category/Fiction">Books <ChevronDown size={14} /></Link><Link to="/category/Self Help">Self development</Link><Link to="/category/Children">Children</Link><Link to="/category/Art & Design">Art & design</Link><Link to="/category/Science">Academic</Link><Link to="/request">Request a book</Link><span className="nav-note">Free delivery over Rs 2,500</span></nav>
  </>
}
function CartDrawer({ open, onClose }) { const { cart, removeFromCart } = useStore(); const total = cart.reduce((sum, item) => sum + item.price * item.qty, 0); return <><div className={`drawer-backdrop ${open ? 'visible' : ''}`} onClick={onClose}></div><aside className={`cart-drawer ${open ? 'open' : ''}`}><div className="drawer-head"><div><p className="eyebrow">Your reading list</p><h2>Bag <span>{cart.length} items</span></h2></div><button onClick={onClose}><X /></button></div>{cart.length ? <><div className="drawer-items">{cart.map(item => <div className="drawer-item" key={item.id}><img src={item.image} alt="" /><div><b>{item.title}</b><small>{item.author}</small><span>{item.qty} × {money(item.price)}</span></div><button onClick={() => removeFromCart(item.id)}><X size={15} /></button></div>)}</div><div className="drawer-footer"><div><span>Subtotal</span><strong>{money(total)}</strong></div><Link to="/checkout" onClick={onClose} className="primary-btn">Continue to checkout <ArrowRight size={16} /></Link><p>Taxes and delivery calculated at checkout.</p></div></> : <div className="empty-cart"><ShoppingBag size={36} /><h3>Your bag is waiting</h3><p>Good books have a way of finding us at the right time.</p><button className="outline-btn" onClick={onClose}>Keep exploring</button></div>}</aside></> }
function ProductCard({ book }) { const { addToCart, wishlist, toggleWishlist } = useStore(); const saved = wishlist.some(item => item.id === book.id); return <article className="product-card"><div className="book-cover" style={{ background: book.accent }}><Link to={`/product/${book.id}`}><img src={book.image} alt={book.title} /></Link><span className="badge">{book.badge}</span><button className={`heart-btn ${saved ? 'saved' : ''}`} onClick={() => toggleWishlist(book)}><Heart size={17} fill={saved ? 'currentColor' : 'none'} /></button></div><div className="product-meta"><span className="category-label">{book.category}</span><Link to={`/product/${book.id}`} className="book-title">{book.title}</Link><span className="author">{book.author}</span><div className="price-row"><strong>{money(book.price)}</strong><del>{money(book.oldPrice)}</del></div><button className="add-btn" onClick={() => addToCart(book)}>Add to bag <span>+</span></button></div></article> }
function SectionHeader({ eyebrow, title, to = '/search' }) { return <div className="section-head"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div><Link to={to}>View all <ArrowRight size={16} /></Link></div> }
function Home() { const [cartOpen, setCartOpen] = useState(false); return <div><Header onCart={() => setCartOpen(true)} /><main><section className="hero"><div className="hero-copy"><p className="eyebrow">A good book changes everything</p><h1>Find the story<br /><i>that finds you.</i></h1><p className="hero-text">Thoughtful books for curious minds. Explore new voices, timeless classics, and the next great read for your shelf.</p><div className="hero-actions"><Link className="primary-btn" to="/search">Explore the collection <ArrowRight size={17} /></Link><Link className="text-link" to="/category/Fiction">Browse fiction</Link></div><div className="hero-proof"><span><strong>50k+</strong> titles to discover</span><span><strong>Since 1952</strong> serving readers</span></div></div><div className="hero-art"><div className="sun"></div><img src="https://images.unsplash.com/photo-1507842217343-583bb7270b66?auto=format&fit=crop&w=1100&q=90" alt="A quiet library filled with books" /><div className="hero-note"><Sparkles size={17} /><span>Make space<br />for wonder.</span></div></div></section>
      <section className="collection-strip"><div className="strip-intro"><Sparkles size={18} /><span>Browse by mood</span></div>{collections.map((name, i) => <Link key={name} to={`/category/${name}`}><span className={`collection-dot dot-${i}`}></span>{name}</Link>)}<ArrowRight className="strip-arrow" size={18} /></section>
      <section className="page-section"><SectionHeader eyebrow="Handpicked for you" title="Fresh on the shelf" /><div className="product-grid featured-grid">{books.slice(0, 4).map(book => <ProductCard key={book.id} book={book} />)}</div></section>
      <section className="editorial-band"><div className="editorial-image"><img src="https://images.unsplash.com/photo-1521587760476-6c12a4b040da?auto=format&fit=crop&w=1000&q=85" alt="Bookshelves in a warm library" /></div><div className="editorial-copy"><p className="eyebrow">The reader's edit</p><h2>Books to help you slow down, look closer, and think bigger.</h2><p>Some books entertain us. The best ones quietly rearrange the furniture in our minds. Our editors gathered a shelf of thoughtful reads for the season ahead.</p><Link className="text-link" to="/search">Meet the edit <ArrowRight size={16} /></Link></div></section>
      <section className="page-section"><SectionHeader eyebrow="Worth making time for" title="Popular this week" to="/category/Bestsellers" /><div className="product-grid">{books.slice(4).map(book => <ProductCard key={book.id} book={book} />)}</div></section>
      <section className="category-section page-section"><SectionHeader eyebrow="Start somewhere wonderful" title="Shop by category" /> <div className="category-grid">{categories.map(([name, copy, image]) => <Link className="category-tile" to={`/category/${name}`} key={name}><img src={image} alt="" /><div><span>{copy}</span><h3>{name}</h3><b>Explore <ArrowRight size={15} /></b></div></Link>)}</div></section>
      <section className="newsletter"><div><p className="eyebrow">A note from our shelves</p><h2>Stories worth knowing about.</h2><p>Monthly recommendations, new arrivals, and a little inspiration for your reading life.</p></div><form onSubmit={e => { e.preventDefault(); e.currentTarget.querySelector('button').textContent = 'You’re on the list' }}><input type="email" required placeholder="Your email address" /><button className="primary-btn">Subscribe <ArrowRight size={16} /></button></form></section>
    </main><Footer /><CartDrawer open={cartOpen} onClose={() => setCartOpen(false)} /><MobileNav /></div> }
function Listing({ search = false }) { const { onCart } = { onCart: () => {} }; const location = useLocation(); const params = useParams(); const term = new URLSearchParams(location.search).get('q'); const title = search ? `Results for “${term || ''}”` : params.slug; const filtered = books.filter(book => !term || `${book.title} ${book.author} ${book.category}`.toLowerCase().includes(term.toLowerCase())).filter(book => !params.slug || params.slug.toLowerCase() === 'bestsellers' || book.category.toLowerCase() === params.slug.toLowerCase()); return <><Header onCart={onCart} /><main className="listing-page page-section"><div className="listing-heading"><div><p className="eyebrow">The library</p><h1>{title}</h1><p>{filtered.length} books ready to discover</p></div><select defaultValue="featured"><option value="featured">Sort: Featured</option><option>Price: Low to high</option><option>Newest first</option></select></div><div className="listing-layout"><aside className="filters"><p className="eyebrow">Refine by</p><b>Format</b><label><input type="checkbox" /> Paperback</label><label><input type="checkbox" /> Hardcover</label><label><input type="checkbox" /> E-book</label><b>Availability</b><label><input type="checkbox" /> In stock</label></aside><div className="product-grid listing-grid">{filtered.map(book => <ProductCard key={book.id} book={book} />)}</div></div></main><Footer /><MobileNav /></> }
function ProductDetail() { const book = books.find(item => item.id === Number(useParams().id)) || books[0]; const { addToCart } = useStore(); return <><Header onCart={() => {}} /><main className="detail-page page-section"><Link className="back-link" to="/search">← Back to the collection</Link><div className="detail-layout"><div className="detail-image" style={{ background: book.accent }}><img src={book.image} alt={book.title} /></div><div className="detail-copy"><p className="eyebrow">{book.category} · {book.badge}</p><h1>{book.title}</h1><p className="detail-author">By <u>{book.author}</u></p><div className="rating"><Star size={16} fill="currentColor" /> <b>4.8</b> <span>128 reader reviews</span></div><div className="detail-price"><strong>{money(book.price)}</strong><del>{money(book.oldPrice)}</del><span>Save {money(book.oldPrice - book.price)}</span></div><p className="detail-description">A beautifully produced edition for readers who like to keep good company on their shelf. Discover a book that stays with you long after the final page.</p><div className="stock"><span></span> In stock and ready to dispatch</div><button className="primary-btn large-btn" onClick={() => addToCart(book)}>Add to bag <ShoppingBag size={17} /></button><div className="delivery-note"><Truck size={19} /><span><b>Free delivery</b> on orders over Rs 2,500<br /><small>Usually arrives in 2–4 working days</small></span></div></div></div><section className="detail-lower"><div><p className="eyebrow">Details</p><h2>A book to return to.</h2></div><p>There are books we read once, and books we carry around for years. This is an invitation to slow down, underline a few sentences, and leave the final page a little different from the first.</p></section></main><Footer /><MobileNav /></> }
function Footer() { return <footer><div className="footer-top"><div className="footer-brand"><Link className="brand" to="/"><span className="brand-mark"><BookOpen size={22} /></span><span>LIBERTY<small>BOOKS</small></span></Link><p>For every curious mind, a better book is waiting.</p></div><div><b>Explore</b><Link to="/search">All books</Link><Link to="/category/Fiction">Fiction</Link><Link to="/category/Children">Children's books</Link></div><div><b>Help</b><Link to="/request">Request a book</Link><Link to="/contact">Contact us</Link><Link to="/track">Track an order</Link></div><div><b>Stay in touch</b><p>hello@liberty-demo.pk<br />+92 21 111 444 111</p><div className="socials"><span>ig</span><span>fb</span><span>in</span></div></div></div><div className="footer-bottom"><span>© 2026 Liberty Books demo. Built with original placeholder content.</span><span>Secure checkout &nbsp; · &nbsp; Easy returns</span></div></footer> }
function MobileNav() { return <nav className="mobile-nav"><Link to="/"><BookOpen size={19} /><span>Home</span></Link><Link to="/search"><Search size={19} /><span>Search</span></Link><Link to="/wishlist"><Heart size={19} /><span>Saved</span></Link><Link to="/login"><Menu size={19} /><span>Menu</span></Link></nav> }
function SimplePage({ title, label }) { return <><Header onCart={() => {}} /><main className="simple-page page-section"><p className="eyebrow">{label}</p><h1>{title}</h1><p>This demo page is ready for your client content. The storefront navigation, responsive layout, and shopping interactions are already wired up.</p><Link className="primary-btn" to="/">Return home <ArrowRight size={16} /></Link></main><Footer /><MobileNav /></> }
function App() { return <StoreProvider><Routes><Route path="/" element={<Home />} /><Route path="/search" element={<Listing search />} /><Route path="/category/:slug" element={<Listing />} /><Route path="/product/:id" element={<ProductDetail />} /><Route path="/wishlist" element={<SimplePage title="Saved for later" label="Your wishlist" />} /><Route path="/login" element={<SimplePage title="Welcome back" label="Account" />} /><Route path="/request" element={<SimplePage title="Request a book" label="Can't find what you're looking for?" />} /><Route path="/contact" element={<SimplePage title="Let's talk books" label="Contact" />} /><Route path="/track" element={<SimplePage title="Track your order" label="Delivery" />} /><Route path="*" element={<SimplePage title="Page not found" label="404" />} /></Routes></StoreProvider> }
createRoot(document.getElementById('root')).render(<BrowserRouter><App /></BrowserRouter>)
